## Numpy Basic
### Numpy的ndarray: 多维数组对象
>ndarray是一个通用的同构数据多维容器，其中的所有元素必须是相同类型。每一个数组有一个shape（一个表示各维度大小的元组）和一个dtype（一个用于说明数据数据类型的对象）
#### 1. 创建ndarray
>array()函数，他接受一切序列型的对象（包括其他数组），然后产生一个新的含有传入数据的Numpy数组,np.array会尝试为新数组推断出一个较为合适的数据类型

In [1]:
import numpy as np

In [2]:
data1 = [6,7.5,8,0,1]

In [3]:
arr1 = np.array(data1)

In [4]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [5]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)

In [6]:
arr2.ndim

2

In [7]:
arr2.shape

(2, 4)

In [8]:
arr1.dtype

dtype('float64')

In [9]:
arr2.dtype

dtype('int32')

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.empty((2,3,2))

array([[[7.23674587e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.78022341e-306, 1.20886213e+161]],

       [[9.91381694e+164, 4.46589521e-033],
        [1.53486516e-075, 7.40353016e-038],
        [4.17824339e-062, 5.73824714e+174]]])

#### 2. ndarray的数据类型

In [20]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int32')

In [22]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [23]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [24]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [25]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [26]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [29]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [30]:
x = int_array.astype(calibers.dtype)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
x.dtype

dtype('float64')

#### 3. 数组和标量之间的运算

In [32]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [33]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [34]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [36]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [37]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [38]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

#### 4. 索引切片

In [39]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr[5]

5

In [41]:
arr[5:8]

array([5, 6, 7])

In [42]:
arr[5:8] = 12

In [43]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [44]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [45]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [46]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [47]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [48]:
#arr2d[0][2]
arr2d[0, 2]

3

In [49]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
old_values = arr3d[0].copy()
arr3d[0] = 42

In [52]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [54]:
arr3d[1, 0]

array([7, 8, 9])

##### 4.1 切片索引

In [55]:
arr
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [56]:
arr2d
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [58]:
arr2d[1, :2]

array([4, 5])

In [59]:
arr2d[:2, 2]

array([3, 6])

In [60]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [61]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

##### 4.2 布尔型索引

In [62]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [63]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [64]:
data

array([[-0.35173324,  0.16866594, -0.8528149 ,  0.16134808],
       [ 0.74648132,  1.1353054 , -0.92619315,  1.13081334],
       [-1.92258172,  1.46340882,  0.65344767, -0.60366905],
       [ 2.05363393, -1.62711672,  2.44709196,  0.90972979],
       [-0.29283249,  0.23965262, -0.03097122, -1.66943956],
       [-0.81267873, -1.67324887,  0.50610367,  0.19153736],
       [-0.16155427,  0.76439028,  0.07051827,  0.20287921]])

In [65]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [66]:
data[names == 'Bob']

array([[-0.35173324,  0.16866594, -0.8528149 ,  0.16134808],
       [ 2.05363393, -1.62711672,  2.44709196,  0.90972979]])

In [67]:
data[names == 'Bob', 2:]

array([[-0.8528149 ,  0.16134808],
       [ 2.44709196,  0.90972979]])

In [68]:
data[~(names == 'Bob')]

array([[ 0.74648132,  1.1353054 , -0.92619315,  1.13081334],
       [-1.92258172,  1.46340882,  0.65344767, -0.60366905],
       [-0.29283249,  0.23965262, -0.03097122, -1.66943956],
       [-0.81267873, -1.67324887,  0.50610367,  0.19153736],
       [-0.16155427,  0.76439028,  0.07051827,  0.20287921]])

In [70]:
data[names != 'Bob']

array([[ 0.74648132,  1.1353054 , -0.92619315,  1.13081334],
       [-1.92258172,  1.46340882,  0.65344767, -0.60366905],
       [-0.29283249,  0.23965262, -0.03097122, -1.66943956],
       [-0.81267873, -1.67324887,  0.50610367,  0.19153736],
       [-0.16155427,  0.76439028,  0.07051827,  0.20287921]])

In [71]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [72]:
data[mask]

array([[-0.35173324,  0.16866594, -0.8528149 ,  0.16134808],
       [-1.92258172,  1.46340882,  0.65344767, -0.60366905],
       [ 2.05363393, -1.62711672,  2.44709196,  0.90972979],
       [-0.29283249,  0.23965262, -0.03097122, -1.66943956]])

##### 4.3 花式索引

In [73]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [74]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [75]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [76]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [77]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [78]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

#### 5. 数组转置与轴对换

In [79]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [80]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [81]:
arr = np.random.randn(6, 3)
arr

array([[ 0.07502022, -0.30101243,  0.94556103],
       [ 0.70841697,  2.15710589, -1.72022941],
       [ 0.06738525, -1.20797571,  0.19949299],
       [-0.18013797,  0.45886375,  1.76675109],
       [ 0.85327463,  0.87903596, -0.81696369],
       [-1.61075302, -2.32015227, -1.01392529]])

In [82]:
np.dot(arr.T, arr)

array([[ 3.86707597,  5.82874123, -0.51643075],
       [ 5.82874123, 12.56928633, -1.79130665],
       [-0.51643075, -1.79130665,  8.70995592]])

In [83]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [84]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

#### 6. 通用函数

In [85]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [87]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [88]:
x = np.random.randn(8)
y = np.random.randn(8)

In [89]:
x

array([ 1.07007029, -1.18425077, -0.09394796, -0.45417077, -0.96323074,
        1.09695207,  2.1365881 ,  0.60694173])

In [90]:
y

array([-0.39710095,  0.65307822,  0.77504121, -1.88700073, -0.43422496,
        1.20671966, -1.61933948,  0.04044302])

In [91]:
np.maximum(x, y)

array([ 1.07007029,  0.65307822,  0.77504121, -0.45417077, -0.43422496,
        1.20671966,  2.1365881 ,  0.60694173])

In [92]:
arr = np.random.randn(7) * 5
arr

array([-6.43669684,  5.00369491, 12.24113049, -0.63401063, -6.0805575 ,
        5.07055685, -2.23555634])

In [93]:
remainder, whole_part = np.modf(arr)

In [94]:
remainder

array([-0.43669684,  0.00369491,  0.24113049, -0.63401063, -0.0805575 ,
        0.07055685, -0.23555634])

In [95]:
whole_part

array([-6.,  5., 12., -0., -6.,  5., -2.])

#### 7. np.where()