### 1. Series

In [2]:
from pandas import Series,DataFrame
import numpy as np
import pandas as pd

In [2]:
obj = Series([4,7,-5,3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj2 = Series([4,7,-5,3],index=['d','b','a','c'])

In [7]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [9]:
obj2.values

array([ 4,  7, -5,  3], dtype=int64)

In [10]:
obj2['a']

-5

In [11]:
obj2['d'] = 6

In [12]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [13]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [14]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [15]:
'b' in obj2

True

In [16]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [17]:
3 in obj2

False

In [18]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [19]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [20]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [21]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [22]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [23]:
obj4.name = 'population'
obj4.index.name = 'state'

In [24]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

### 2. DataFrame

In [25]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
df = pd.DataFrame(data)

In [26]:
df

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [27]:
DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [48]:
df2 = DataFrame(data,columns=['year','state','pop','debt'],index=['zero','one','two','three','four','five'])
df2

year   state  pop debt
zero   2000    Ohio  1.5  NaN
one    2001    Ohio  1.7  NaN
two    2002    Ohio  3.6  NaN
three  2001  Nevada  2.4  NaN
four   2002  Nevada  2.9  NaN
five   2003  Nevada  3.2  NaN

In [49]:
df2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [50]:
df2.index

Index(['zero', 'one', 'two', 'three', 'four', 'five'], dtype='object')

In [51]:
df2['state']

zero       Ohio
one        Ohio
two        Ohio
three    Nevada
four     Nevada
five     Nevada
Name: state, dtype: object

In [52]:
df2.year

zero     2000
one      2001
two      2002
three    2001
four     2002
five     2003
Name: year, dtype: int64

In [53]:
df2.loc['one']

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: one, dtype: object

In [54]:
df2['debt'] = 16.5
df2

year   state  pop  debt
zero   2000    Ohio  1.5  16.5
one    2001    Ohio  1.7  16.5
two    2002    Ohio  3.6  16.5
three  2001  Nevada  2.4  16.5
four   2002  Nevada  2.9  16.5
five   2003  Nevada  3.2  16.5

In [55]:
import numpy as np
df2['debt'] = np.arange(6.)
df2

year   state  pop  debt
zero   2000    Ohio  1.5   0.0
one    2001    Ohio  1.7   1.0
two    2002    Ohio  3.6   2.0
three  2001  Nevada  2.4   3.0
four   2002  Nevada  2.9   4.0
five   2003  Nevada  3.2   5.0

In [56]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
df2['debt'] = val

In [58]:
df2

year   state  pop  debt
zero   2000    Ohio  1.5   NaN
one    2001    Ohio  1.7   NaN
two    2002    Ohio  3.6  -1.2
three  2001  Nevada  2.4   NaN
four   2002  Nevada  2.9  -1.5
five   2003  Nevada  3.2  -1.7

In [59]:
df2['eastern']=df2.state=='Ohio'
df2

year   state  pop  debt  eastern
zero   2000    Ohio  1.5   NaN     True
one    2001    Ohio  1.7   NaN     True
two    2002    Ohio  3.6  -1.2     True
three  2001  Nevada  2.4   NaN    False
four   2002  Nevada  2.9  -1.5    False
five   2003  Nevada  3.2  -1.7    False

In [60]:
del df2['eastern']

In [61]:
df2

year   state  pop  debt
zero   2000    Ohio  1.5   NaN
one    2001    Ohio  1.7   NaN
two    2002    Ohio  3.6  -1.2
three  2001  Nevada  2.4   NaN
four   2002  Nevada  2.9  -1.5
five   2003  Nevada  3.2  -1.7

In [62]:
df2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, -1.2],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, -1.5],
       [2003, 'Nevada', 3.2, -1.7]], dtype=object)

#### 3. 索引对象

In [63]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [64]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [65]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [66]:
obj2.index is labels

True

#### 4.其他功能

##### 4.1 重新索引

In [67]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [68]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [72]:
obj.reindex(['a', 'b', 'c', 'd', 'e'],fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [69]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [71]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [73]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [74]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [75]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [78]:
frame.loc[['a', 'b', 'c', 'd'], states]

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

##### 4.2 丢弃指定轴上的项

In [79]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [80]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [81]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [82]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [83]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [84]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [85]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [86]:
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

##### 4.3 索引，选取和过滤

In [87]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [88]:
obj['b']

1.0

In [89]:
obj[1]

1.0

In [90]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [91]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [92]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [93]:
obj < 2

a     True
b     True
c    False
d    False
dtype: bool

In [94]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [95]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [96]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [97]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [98]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [99]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [100]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [102]:
data['three'] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [103]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [104]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [105]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

##### 4.4 行上索引 loc and iloc

In [106]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [107]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [108]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [109]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [110]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [111]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

##### 4.5 算数运算和数据对齐

In [112]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])

In [113]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [114]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [115]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [116]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [117]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [118]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [119]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

##### 4.6在算数方法中填充值

In [120]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))

In [121]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [122]:
df2.loc[1, 'b'] = np.nan

In [123]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [124]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

##### 4.7 DataFrame和Series之间的运算

In [125]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [126]:
arr[0]

array([0., 1., 2., 3.])

In [127]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [128]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [129]:
series = frame.iloc[0]

In [130]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [131]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [132]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [133]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [134]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [135]:
frame + series3

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [136]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [137]:
frame.sub(series3, axis='columns')

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [138]:
frame.sub(series3)

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

##### 4.8函数应用和映射

In [5]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -1.798004 -0.178344 -0.567192
Ohio   -0.301083 -0.687536 -0.450053
Texas  -0.258055 -1.028957 -0.076864
Oregon -0.513083  1.712471  0.356593

In [6]:
np.abs(frame)

b         d         e
Utah    1.798004  0.178344  0.567192
Ohio    0.301083  0.687536  0.450053
Texas   0.258055  1.028957  0.076864
Oregon  0.513083  1.712471  0.356593

In [7]:
f = lambda x: x.max() - x.min()
f

<function __main__.<lambda>(x)>

In [8]:
frame.apply(f)

b    1.539949
d    2.741427
e    0.923785
dtype: float64

In [9]:
frame.apply(f, axis='columns')

Utah      1.619660
Ohio      0.386453
Texas     0.952093
Oregon    2.225553
dtype: float64

In [10]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -1.798004 -1.028957 -0.567192
max -0.258055  1.712471  0.356593

In [11]:
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah    -1.80  -0.18  -0.57
Ohio    -0.30  -0.69  -0.45
Texas   -0.26  -1.03  -0.08
Oregon  -0.51   1.71   0.36

In [12]:
frame['e'].map(format)

Utah      -0.57
Ohio      -0.45
Texas     -0.08
Oregon     0.36
Name: e, dtype: object

##### 4.9 排序和排名

In [13]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [14]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [15]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [16]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [17]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [18]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [19]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [20]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [23]:
frame.sort_values(by=['b'])

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [24]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [25]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [26]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [27]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [28]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

##### 4.10带有重复值的轴索引

In [29]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [30]:
obj.index.is_unique

False

In [31]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a -0.603819 -0.392018 -1.166849
a -0.259751  0.353391 -1.017248
b  0.727500  0.248039  1.199312
b -0.705201 -0.979281 -1.936207

In [32]:
df.loc['b']

0         1         2
b  0.727500  0.248039  1.199312
b -0.705201 -0.979281 -1.936207

#### 5. 计算统计

In [33]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [34]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [35]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [36]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [37]:
# 获取文件中的股票数据
price = pd.read_pickle('examples/yahoo_price.pkl')
volume = pd.read_pickle('examples/yahoo_volume.pkl')

In [38]:
price

AAPL        GOOG         IBM       MSFT
Date                                                     
2010-01-04   27.990226  313.062468  113.304536  25.884104
2010-01-05   28.038618  311.683844  111.935822  25.892466
2010-01-06   27.592626  303.826685  111.208683  25.733566
2010-01-07   27.541619  296.753749  110.823732  25.465944
2010-01-08   27.724725  300.709808  111.935822  25.641571
...                ...         ...         ...        ...
2016-10-17  117.550003  779.960022  154.770004  57.220001
2016-10-18  117.470001  795.260010  150.720001  57.660000
2016-10-19  117.120003  801.500000  151.259995  57.529999
2016-10-20  117.059998  796.969971  151.520004  57.250000
2016-10-21  116.599998  799.369995  149.630005  59.660000

[1714 rows x 4 columns]

In [40]:
# 获取股票数据，最新数据
import pandas_datareader.data as web 
all_data = {ticker: web.get_data_yahoo(ticker) for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}
price = pd.DataFrame({ticker: data['Adj Close'] for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume'] for ticker, data in all_data.items()})

In [41]:
price

AAPL         IBM        MSFT         GOOG
Date                                                       
2014-11-10   99.994888  131.743423   43.764729   545.990967
2014-11-11  100.794250  131.590302   43.746830   548.783325
2014-11-12  102.218430  130.478241   43.666264   545.811462
2014-11-13  103.660957  131.179306   44.409256   543.886780
2014-11-14  104.910561  132.283310   44.382393   542.909424
...                ...         ...         ...          ...
2019-11-01  255.054260  133.947937  143.720001  1273.739990
2019-11-04  256.729218  136.062958  144.550003  1291.369995
2019-11-05  256.360352  136.280396  144.460007  1292.030029
2019-11-06  256.470001  137.160004  144.059998  1291.800049
2019-11-07  259.429993  137.690002  144.259995  1308.859985

[1258 rows x 4 columns]

In [42]:
returns = price.pct_change()
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2019-11-01  0.028381  0.013460  0.002441  0.010817
2019-11-04  0.006567  0.015790  0.005775  0.013841
2019-11-05 -0.001437  0.001598 -0.000623  0.000511
2019-11-06  0.000428  0.006454 -0.002769 -0.000178
2019-11-07  0.011541  0.003864  0.001388  0.013206

In [43]:
returns['MSFT'].corr(returns['IBM'])

0.48718891645166984

In [44]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.405903  0.570699  0.522465
IBM   0.405903  1.000000  0.487189  0.414022
MSFT  0.570699  0.487189  1.000000  0.657043
GOOG  0.522465  0.414022  0.657043  1.000000

In [45]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000248  0.000083  0.000133  0.000125
IBM   0.000083  0.000170  0.000094  0.000082
MSFT  0.000133  0.000094  0.000219  0.000148
GOOG  0.000125  0.000082  0.000148  0.000231

##### 5.3 唯一值，值计数以及成员关系

In [47]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [48]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [49]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [50]:
pd.value_counts(obj.values, sort=False)

c    3
b    2
a    3
d    1
dtype: int64

In [51]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [52]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [53]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])

In [54]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [55]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [56]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

#### 6. 处理缺失数据

##### 6.1 滤除缺失数据

In [3]:
data = Series([1,np.nan,3.5,np.nan,7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [4]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [5]:
df = DataFrame([[1,6.5,3],[1,np.nan,np.nan],[np.nan,np.nan,np.nan],[np.nan,6.5,3]])
df

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [7]:
cleaned = df.dropna()
cleaned

0    1    2
0  1.0  6.5  3.0

In [8]:
cleaned1 = df.dropna(how='all')
cleaned1

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [9]:
df[4] = np.nan
df

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [10]:
cleaned2 = df.dropna(axis=1,how='all')
cleaned2

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [11]:
df.fillna(0)

0    1    2    4
0  1.0  6.5  3.0  0.0
1  1.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  0.0  6.5  3.0  0.0

#### 7. 层次化索引

In [12]:
s = Series(np.random.randn(10),index=[['a','a','a','b','b','b','c','c','d','d'],[1,2,3,1,2,3,1,2,2,3]])
s

a  1    0.246249
   2   -1.562345
   3   -0.721114
b  1   -2.398293
   2   -0.286601
   3    0.471695
c  1   -0.315619
   2   -1.125934
d  2   -1.815897
   3   -0.804295
dtype: float64

In [13]:
data.index

RangeIndex(start=0, stop=5, step=1)

In [14]:
s.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 2),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )